using System.Globalization;

namespace KiwixConverter.WinForms;

internal sealed class UiLocalizer
{
    private static readonly IReadOnlyDictionary<string, string> SimplifiedChinese = new Dictionary<string, string>
    {
        ["Kiwix Converter"] = "Kiwix 转换器",
        ["Kiwix Converter v{0}"] = "Kiwix 转换器 v{0}",
        ["ZIM to Markdown, RAG artifacts, and WeKnora sync"] = "ZIM 转 Markdown、RAG 产物与 WeKnora 同步",
        ["Version {0}"] = "版本 {0}",
        ["Search by path, status, output directory or error..."] = "按路径、状态、输出目录或错误搜索...",
        ["Search logs by message, category or article URL..."] = "按消息、类别或文章 URL 搜索日志...",
        ["Save Settings"] = "保存设置",
        ["Scan ZIM Files"] = "扫描 ZIM 文件",
        ["Convert Selected ZIM"] = "转换所选 ZIM",
        ["Pause Selected Task"] = "暂停所选任务",
        ["Resume Selected Task"] = "恢复所选任务",
        ["Refresh History"] = "刷新历史",
        ["Refresh Logs"] = "刷新日志",
        ["Selected task only"] = "仅所选任务",
        ["Directories And Tooling"] = "目录与工具",
        ["Browse..."] = "浏览...",
        ["Default Output"] = "默认输出",
        ["zimdump Path"] = "zimdump 路径",
        ["Snapshot Seconds"] = "快照秒数",
        ["Article-level checkpoints + periodic task snapshots"] = "文章级检查点 + 周期性任务快照",
        ["Per-Task Output Override"] = "单任务输出覆盖",
        ["Output Override"] = "输出覆盖",
        ["Leave empty to use the default output directory. Each ZIM is exported into its own subdirectory."] = "留空时使用默认输出目录。每个 ZIM 会导出到独立子目录。",
        ["Downloaded ZIM Files"] = "已下载 ZIM 文件",
        ["Completed items are marked directly in this list. Select one row and start a conversion from the override panel above."] = "已完成项目会直接在此列表中标记。选择一行后可从上方覆盖面板启动转换。",
        ["Tasks"] = "任务",
        ["Running tasks auto-save progress before exit and resume from article checkpoints."] = "运行中的任务会在退出前自动保存进度，并从文章检查点继续。",
        ["History"] = "历史",
        ["Keyword"] = "关键字",
        ["Logs"] = "日志",
        ["Search"] = "搜索",
        ["Select a task row to filter logs by task ID."] = "选择任务行后可按任务 ID 过滤日志。",
        ["WeKnora Sync Configuration"] = "WeKnora 同步配置",
        ["Base URL"] = "基础 URL",
        ["The app accepts either the root URL or a full /api/v1 URL."] = "应用同时接受根 URL 和完整 /api/v1 URL。",
        ["Auth Mode"] = "认证方式",
        ["Use API Key for tenant keys or Bearer Token for JWT-style deployments."] = "租户密钥使用 API Key，JWT 风格部署使用 Bearer Token。",
        ["Access Token"] = "访问令牌",
        ["Knowledge Base"] = "知识库",
        ["KB Name"] = "知识库名称",
        ["KB ID"] = "知识库 ID",
        ["Optional exact target. Leave empty to match by name."] = "可选精确目标。留空则按名称匹配。",
        ["KB Description"] = "知识库描述",
        ["Used when creating or auto-creating a knowledge base."] = "创建或自动创建知识库时使用。",
        ["Chunk Size"] = "分块大小",
        ["Chunk size for new knowledge bases."] = "新建知识库的分块大小。",
        ["Chunk Overlap"] = "分块重叠",
        ["Overlap applied between adjacent chunks."] = "相邻分块之间应用的重叠。",
        ["Chat Model ID"] = "对话模型 ID",
        ["Embedding Model ID"] = "Embedding 模型 ID",
        ["Optional Embedding model from /api/v1/models. Leave empty to use the server default."] = "可选的 /api/v1/models Embedding 模型。留空则使用服务器默认值。",
        ["Multimodal ID"] = "多模态 ID",
        ["Optional VLLM model from /api/v1/models."] = "可选的 /api/v1/models VLLM 模型。",
        ["Auto-create the knowledge base when the configured name does not exist"] = "当配置名称不存在时自动创建知识库",
        ["Append export metadata to the synced Markdown content"] = "将导出元数据附加到同步的 Markdown 内容中",
        ["Enable parent-child chunking for newly created knowledge bases"] = "为新建知识库启用父子分块",
        ["Test Connection"] = "测试连接",
        ["Load Knowledge Bases"] = "加载知识库",
        ["Load Models"] = "加载模型",
        ["Create KB"] = "创建知识库",
        ["WeKnora Sync"] = "WeKnora 同步",
        ["Select one or more completed conversion outputs, start a sync, then watch progress, ETA, logs, and resume state from the same screen."] = "选择一个或多个已完成转换的输出，启动同步后即可在同一界面查看进度、预计剩余时间、日志和恢复状态。",
        ["Sync Selected Archives"] = "同步所选归档",
        ["Pause Selected Sync"] = "暂停所选同步",
        ["Resume Selected Sync"] = "恢复所选同步",
        ["Refresh Sync View"] = "刷新同步视图",
        ["Select rows in the candidate grid to create sync tasks."] = "在候选列表中选择行以创建同步任务。",
        ["Converted Archives Ready To Sync"] = "可同步的已转换归档",
        ["Each row represents a completed conversion task. The sync task will upload every completed article export from the selected archive to the configured WeKnora knowledge base."] = "每一行代表一个已完成的转换任务。同步任务会把所选归档中的所有已完成文章导出上传到配置好的 WeKnora 知识库。",
        ["WeKnora Sync Tasks"] = "WeKnora 同步任务",
        ["WeKnora Sync Logs"] = "WeKnora 同步日志",
        ["Search sync tasks by archive, knowledge base, status or error..."] = "按归档、知识库、状态或错误搜索同步任务...",
        ["Search WeKnora sync logs by message or article URL..."] = "按消息或文章 URL 搜索 WeKnora 同步日志...",
        ["Selected sync only"] = "仅所选同步",
        ["No WeKnora sync task selected."] = "未选择 WeKnora 同步任务。",
        ["Select a sync task row to scope logs."] = "选择同步任务行后可限定日志范围。",
        ["Use Refresh Sync View after changing filters."] = "修改筛选条件后请使用“刷新同步视图”。",
        ["Choose an existing knowledge base from the server, or type a new KB name and click Create KB. New knowledge bases use the description, chunk size, chunk overlap, and parent-child settings above. Use Load Models to fetch live KnowledgeQA, Embedding, and VLLM model IDs from WeKnora before creating a KB or starting a sync."] = "从服务器中选择已有知识库，或输入新的知识库名称并点击“创建知识库”。新建知识库会使用上方的描述、分块大小、分块重叠和父子分块设置。创建知识库或启动同步前，可使用“加载模型”获取实时的 KnowledgeQA、Embedding 和 VLLM 模型 ID。"
    };

    private static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string>
    {
        ["Kiwix Converter"] = "Kiwix コンバーター",
        ["Kiwix Converter v{0}"] = "Kiwix コンバーター v{0}",
        ["ZIM to Markdown, RAG artifacts, and WeKnora sync"] = "ZIM から Markdown、RAG 成果物、WeKnora 同期へ",
        ["Version {0}"] = "バージョン {0}",
        ["Search by path, status, output directory or error..."] = "パス、状態、出力先、エラーで検索...",
        ["Search logs by message, category or article URL..."] = "メッセージ、カテゴリ、記事 URL でログ検索...",
        ["Save Settings"] = "設定を保存",
        ["Scan ZIM Files"] = "ZIM ファイルをスキャン",
        ["Convert Selected ZIM"] = "選択した ZIM を変換",
        ["Pause Selected Task"] = "選択タスクを一時停止",
        ["Resume Selected Task"] = "選択タスクを再開",
        ["Refresh History"] = "履歴を更新",
        ["Refresh Logs"] = "ログを更新",
        ["Selected task only"] = "選択タスクのみ",
        ["Directories And Tooling"] = "ディレクトリとツール",
        ["Browse..."] = "参照...",
        ["Default Output"] = "既定の出力先",
        ["zimdump Path"] = "zimdump パス",
        ["Snapshot Seconds"] = "スナップショット秒数",
        ["Article-level checkpoints + periodic task snapshots"] = "記事単位チェックポイント + 定期タスクスナップショット",
        ["Per-Task Output Override"] = "タスク単位の出力上書き",
        ["Output Override"] = "出力上書き",
        ["Leave empty to use the default output directory. Each ZIM is exported into its own subdirectory."] = "空欄のままにすると既定の出力先を使用します。各 ZIM は専用サブディレクトリへ出力されます。",
        ["Downloaded ZIM Files"] = "ダウンロード済み ZIM ファイル",
        ["Completed items are marked directly in this list. Select one row and start a conversion from the override panel above."] = "完了済み項目はこの一覧で直接マークされます。1 行選択して上の上書きパネルから変換を開始してください。",
        ["Tasks"] = "タスク",
        ["Running tasks auto-save progress before exit and resume from article checkpoints."] = "実行中タスクは終了前に進捗を自動保存し、記事チェックポイントから再開します。",
        ["History"] = "履歴",
        ["Keyword"] = "キーワード",
        ["Logs"] = "ログ",
        ["Search"] = "検索",
        ["Select a task row to filter logs by task ID."] = "ログをタスク ID で絞り込むにはタスク行を選択してください。",
        ["WeKnora Sync Configuration"] = "WeKnora 同期設定",
        ["Base URL"] = "ベース URL",
        ["The app accepts either the root URL or a full /api/v1 URL."] = "ルート URL と完全な /api/v1 URL のどちらも利用できます。",
        ["Auth Mode"] = "認証方式",
        ["Use API Key for tenant keys or Bearer Token for JWT-style deployments."] = "テナントキーには API Key、JWT 形式の構成には Bearer Token を使用します。",
        ["Access Token"] = "アクセストークン",
        ["Knowledge Base"] = "ナレッジベース",
        ["KB Name"] = "KB 名",
        ["KB ID"] = "KB ID",
        ["Optional exact target. Leave empty to match by name."] = "正確な対象を指定する任意項目です。空欄なら名前で一致させます。",
        ["KB Description"] = "KB 説明",
        ["Used when creating or auto-creating a knowledge base."] = "ナレッジベース作成時または自動作成時に使用します。",
        ["Chunk Size"] = "チャンクサイズ",
        ["Chunk size for new knowledge bases."] = "新しいナレッジベースのチャンクサイズです。",
        ["Chunk Overlap"] = "チャンク重なり",
        ["Overlap applied between adjacent chunks."] = "隣接チャンク間に適用される重なりです。",
        ["Chat Model ID"] = "チャットモデル ID",
        ["Embedding Model ID"] = "Embedding モデル ID",
        ["Optional Embedding model from /api/v1/models. Leave empty to use the server default."] = "/api/v1/models の Embedding モデルを任意指定できます。空欄ならサーバー既定値を使います。",
        ["Multimodal ID"] = "マルチモーダル ID",
        ["Optional VLLM model from /api/v1/models."] = "/api/v1/models の VLLM モデルを任意指定できます。",
        ["Auto-create the knowledge base when the configured name does not exist"] = "指定名のナレッジベースが存在しない場合は自動作成する",
        ["Append export metadata to the synced Markdown content"] = "同期する Markdown にエクスポートメタデータを追加する",
        ["Enable parent-child chunking for newly created knowledge bases"] = "新規ナレッジベースで親子チャンク化を有効にする",
        ["Test Connection"] = "接続テスト",
        ["Load Knowledge Bases"] = "ナレッジベースを読み込む",
        ["Load Models"] = "モデルを読み込む",
        ["Create KB"] = "KB を作成",
        ["WeKnora Sync"] = "WeKnora 同期",
        ["Select one or more completed conversion outputs, start a sync, then watch progress, ETA, logs, and resume state from the same screen."] = "完了した変換出力を 1 つ以上選択して同期を開始すると、同じ画面で進捗、残り時間、ログ、再開状態を確認できます。",
        ["Sync Selected Archives"] = "選択したアーカイブを同期",
        ["Pause Selected Sync"] = "選択同期を一時停止",
        ["Resume Selected Sync"] = "選択同期を再開",
        ["Refresh Sync View"] = "同期ビューを更新",
        ["Select rows in the candidate grid to create sync tasks."] = "候補グリッドで行を選択して同期タスクを作成します。",
        ["Converted Archives Ready To Sync"] = "同期可能な変換済みアーカイブ",
        ["Each row represents a completed conversion task. The sync task will upload every completed article export from the selected archive to the configured WeKnora knowledge base."] = "各行は完了済み変換タスクを表します。同期タスクは、選択したアーカイブの完了済み記事エクスポートを設定済み WeKnora ナレッジベースへアップロードします。",
        ["WeKnora Sync Tasks"] = "WeKnora 同期タスク",
        ["WeKnora Sync Logs"] = "WeKnora 同期ログ",
        ["Search sync tasks by archive, knowledge base, status or error..."] = "アーカイブ、ナレッジベース、状態、エラーで同期タスクを検索...",
        ["Search WeKnora sync logs by message or article URL..."] = "メッセージまたは記事 URL で WeKnora 同期ログを検索...",
        ["Selected sync only"] = "選択同期のみ",
        ["No WeKnora sync task selected."] = "WeKnora 同期タスクが選択されていません。",
        ["Select a sync task row to scope logs."] = "ログを絞り込むには同期タスク行を選択してください。",
        ["Use Refresh Sync View after changing filters."] = "フィルター変更後は「同期ビューを更新」を使ってください。",
        ["Choose an existing knowledge base from the server, or type a new KB name and click Create KB. New knowledge bases use the description, chunk size, chunk overlap, and parent-child settings above. Use Load Models to fetch live KnowledgeQA, Embedding, and VLLM model IDs from WeKnora before creating a KB or starting a sync."] = "サーバー上の既存ナレッジベースを選ぶか、新しい KB 名を入力して「KB を作成」を押してください。新規ナレッジベースには上記の説明、チャンクサイズ、チャンク重なり、親子チャンク設定が使われます。KB 作成や同期開始の前に「モデルを読み込む」で WeKnora の KnowledgeQA、Embedding、VLLM のモデル ID を取得できます。"
    };

    private static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string>
    {
        ["Kiwix Converter"] = "Convertidor Kiwix",
        ["Kiwix Converter v{0}"] = "Convertidor Kiwix v{0}",
        ["ZIM to Markdown, RAG artifacts, and WeKnora sync"] = "De ZIM a Markdown, artefactos RAG y sincronización con WeKnora",
        ["Version {0}"] = "Versión {0}",
        ["Search by path, status, output directory or error..."] = "Buscar por ruta, estado, directorio de salida o error...",
        ["Search logs by message, category or article URL..."] = "Buscar registros por mensaje, categoría o URL del artículo...",
        ["Save Settings"] = "Guardar configuración",
        ["Scan ZIM Files"] = "Escanear archivos ZIM",
        ["Convert Selected ZIM"] = "Convertir ZIM seleccionado",
        ["Pause Selected Task"] = "Pausar tarea seleccionada",
        ["Resume Selected Task"] = "Reanudar tarea seleccionada",
        ["Refresh History"] = "Actualizar historial",
        ["Refresh Logs"] = "Actualizar registros",
        ["Selected task only"] = "Solo la tarea seleccionada",
        ["Directories And Tooling"] = "Directorios y herramientas",
        ["Browse..."] = "Examinar...",
        ["Default Output"] = "Salida predeterminada",
        ["zimdump Path"] = "Ruta de zimdump",
        ["Snapshot Seconds"] = "Segundos de instantánea",
        ["Article-level checkpoints + periodic task snapshots"] = "Puntos de control por artículo + instantáneas periódicas de tareas",
        ["Per-Task Output Override"] = "Sobrescritura de salida por tarea",
        ["Output Override"] = "Sobrescritura de salida",
        ["Leave empty to use the default output directory. Each ZIM is exported into its own subdirectory."] = "Déjelo vacío para usar el directorio de salida predeterminado. Cada ZIM se exporta a su propio subdirectorio.",
        ["Downloaded ZIM Files"] = "Archivos ZIM descargados",
        ["Completed items are marked directly in this list. Select one row and start a conversion from the override panel above."] = "Los elementos completados se marcan directamente en esta lista. Seleccione una fila e inicie la conversión desde el panel superior.",
        ["Tasks"] = "Tareas",
        ["Running tasks auto-save progress before exit and resume from article checkpoints."] = "Las tareas en ejecución guardan el progreso automáticamente antes de salir y reanudan desde puntos de control por artículo.",
        ["History"] = "Historial",
        ["Keyword"] = "Palabra clave",
        ["Logs"] = "Registros",
        ["Search"] = "Buscar",
        ["Select a task row to filter logs by task ID."] = "Seleccione una fila de tarea para filtrar los registros por ID de tarea.",
        ["WeKnora Sync Configuration"] = "Configuración de sincronización de WeKnora",
        ["Base URL"] = "URL base",
        ["The app accepts either the root URL or a full /api/v1 URL."] = "La aplicación acepta tanto la URL raíz como una URL completa de /api/v1.",
        ["Auth Mode"] = "Modo de autenticación",
        ["Use API Key for tenant keys or Bearer Token for JWT-style deployments."] = "Use API Key para claves de inquilino o Bearer Token para despliegues tipo JWT.",
        ["Access Token"] = "Token de acceso",
        ["Knowledge Base"] = "Base de conocimiento",
        ["KB Name"] = "Nombre de la BC",
        ["KB ID"] = "ID de la BC",
        ["Optional exact target. Leave empty to match by name."] = "Objetivo exacto opcional. Déjelo vacío para coincidir por nombre.",
        ["KB Description"] = "Descripción de la BC",
        ["Used when creating or auto-creating a knowledge base."] = "Se usa al crear o auto-crear una base de conocimiento.",
        ["Chunk Size"] = "Tamaño de fragmento",
        ["Chunk size for new knowledge bases."] = "Tamaño de fragmento para nuevas bases de conocimiento.",
        ["Chunk Overlap"] = "Solapamiento de fragmentos",
        ["Overlap applied between adjacent chunks."] = "Solapamiento aplicado entre fragmentos adyacentes.",
        ["Chat Model ID"] = "ID del modelo de chat",
        ["Embedding Model ID"] = "ID del modelo de embeddings",
        ["Optional Embedding model from /api/v1/models. Leave empty to use the server default."] = "Modelo de embeddings opcional de /api/v1/models. Déjelo vacío para usar el predeterminado del servidor.",
        ["Multimodal ID"] = "ID multimodal",
        ["Optional VLLM model from /api/v1/models."] = "Modelo VLLM opcional de /api/v1/models.",
        ["Auto-create the knowledge base when the configured name does not exist"] = "Crear automáticamente la base de conocimiento cuando el nombre configurado no exista",
        ["Append export metadata to the synced Markdown content"] = "Agregar metadatos de exportación al contenido Markdown sincronizado",
        ["Enable parent-child chunking for newly created knowledge bases"] = "Habilitar fragmentación padre-hijo para bases de conocimiento nuevas",
        ["Test Connection"] = "Probar conexión",
        ["Load Knowledge Bases"] = "Cargar bases de conocimiento",
        ["Load Models"] = "Cargar modelos",
        ["Create KB"] = "Crear BC",
        ["WeKnora Sync"] = "Sincronización con WeKnora",
        ["Select one or more completed conversion outputs, start a sync, then watch progress, ETA, logs, and resume state from the same screen."] = "Seleccione una o varias salidas de conversión completadas, inicie una sincronización y supervise el progreso, ETA, registros y estado de reanudación desde la misma pantalla.",
        ["Sync Selected Archives"] = "Sincronizar archivos seleccionados",
        ["Pause Selected Sync"] = "Pausar sincronización seleccionada",
        ["Resume Selected Sync"] = "Reanudar sincronización seleccionada",
        ["Refresh Sync View"] = "Actualizar vista de sincronización",
        ["Select rows in the candidate grid to create sync tasks."] = "Seleccione filas en la cuadrícula de candidatos para crear tareas de sincronización.",
        ["Converted Archives Ready To Sync"] = "Archivos convertidos listos para sincronizar",
        ["Each row represents a completed conversion task. The sync task will upload every completed article export from the selected archive to the configured WeKnora knowledge base."] = "Cada fila representa una tarea de conversión completada. La tarea de sincronización cargará cada exportación de artículo completada del archivo seleccionado en la base de conocimiento configurada de WeKnora.",
        ["WeKnora Sync Tasks"] = "Tareas de sincronización de WeKnora",
        ["WeKnora Sync Logs"] = "Registros de sincronización de WeKnora",
        ["Search sync tasks by archive, knowledge base, status or error..."] = "Buscar tareas de sincronización por archivo, base de conocimiento, estado o error...",
        ["Search WeKnora sync logs by message or article URL..."] = "Buscar registros de sincronización de WeKnora por mensaje o URL del artículo...",
        ["Selected sync only"] = "Solo sincronización seleccionada",
        ["No WeKnora sync task selected."] = "No hay ninguna tarea de sincronización de WeKnora seleccionada.",
        ["Select a sync task row to scope logs."] = "Seleccione una fila de tarea de sincronización para limitar los registros.",
        ["Use Refresh Sync View after changing filters."] = "Use “Actualizar vista de sincronización” después de cambiar los filtros.",
        ["Choose an existing knowledge base from the server, or type a new KB name and click Create KB. New knowledge bases use the description, chunk size, chunk overlap, and parent-child settings above. Use Load Models to fetch live KnowledgeQA, Embedding, and VLLM model IDs from WeKnora before creating a KB or starting a sync."] = "Elija una base de conocimiento existente del servidor, o escriba un nuevo nombre de BC y haga clic en “Crear BC”. Las nuevas bases de conocimiento usan la descripción, el tamaño de fragmento, el solapamiento y la configuración padre-hijo de arriba. Use “Cargar modelos” para obtener los ID en vivo de KnowledgeQA, Embedding y VLLM de WeKnora antes de crear una BC o iniciar una sincronización."
    };

    private static readonly IReadOnlyDictionary<string, string> Arabic = new Dictionary<string, string>
    {
        ["Kiwix Converter"] = "محول Kiwix",
        ["Kiwix Converter v{0}"] = "محول Kiwix v{0}",
        ["ZIM to Markdown, RAG artifacts, and WeKnora sync"] = "من ZIM إلى Markdown ومخرجات RAG ومزامنة WeKnora",
        ["Version {0}"] = "الإصدار {0}",
        ["Search by path, status, output directory or error..."] = "ابحث حسب المسار أو الحالة أو مجلد الإخراج أو الخطأ...",
        ["Search logs by message, category or article URL..."] = "ابحث في السجلات حسب الرسالة أو الفئة أو رابط المقالة...",
        ["Save Settings"] = "حفظ الإعدادات",
        ["Scan ZIM Files"] = "فحص ملفات ZIM",
        ["Convert Selected ZIM"] = "تحويل ملف ZIM المحدد",
        ["Pause Selected Task"] = "إيقاف المهمة المحددة مؤقتًا",
        ["Resume Selected Task"] = "استئناف المهمة المحددة",
        ["Refresh History"] = "تحديث السجل",
        ["Refresh Logs"] = "تحديث السجلات",
        ["Selected task only"] = "المهمة المحددة فقط",
        ["Directories And Tooling"] = "المجلدات والأدوات",
        ["Browse..."] = "استعراض...",
        ["Default Output"] = "الإخراج الافتراضي",
        ["zimdump Path"] = "مسار zimdump",
        ["Snapshot Seconds"] = "ثواني اللقطة",
        ["Article-level checkpoints + periodic task snapshots"] = "نقاط حفظ على مستوى المقال + لقطات دورية للمهام",
        ["Per-Task Output Override"] = "تجاوز الإخراج لكل مهمة",
        ["Output Override"] = "تجاوز الإخراج",
        ["Leave empty to use the default output directory. Each ZIM is exported into its own subdirectory."] = "اتركه فارغًا لاستخدام مجلد الإخراج الافتراضي. يتم تصدير كل ZIM إلى مجلد فرعي خاص به.",
        ["Downloaded ZIM Files"] = "ملفات ZIM التي تم تنزيلها",
        ["Completed items are marked directly in this list. Select one row and start a conversion from the override panel above."] = "يتم تمييز العناصر المكتملة مباشرة في هذه القائمة. اختر صفًا واحدًا وابدأ التحويل من لوحة التجاوز أعلاه.",
        ["Tasks"] = "المهام",
        ["Running tasks auto-save progress before exit and resume from article checkpoints."] = "تحفظ المهام الجارية التقدم تلقائيًا قبل الإغلاق وتستأنف من نقاط حفظ المقالات.",
        ["History"] = "السجل",
        ["Keyword"] = "الكلمة المفتاحية",
        ["Logs"] = "السجلات",
        ["Search"] = "بحث",
        ["Select a task row to filter logs by task ID."] = "اختر صف مهمة لتصفية السجلات حسب معرّف المهمة.",
        ["WeKnora Sync Configuration"] = "إعدادات مزامنة WeKnora",
        ["Base URL"] = "الرابط الأساسي",
        ["The app accepts either the root URL or a full /api/v1 URL."] = "يدعم التطبيق عنوان الجذر أو عنوان /api/v1 الكامل.",
        ["Auth Mode"] = "وضع المصادقة",
        ["Use API Key for tenant keys or Bearer Token for JWT-style deployments."] = "استخدم API Key لمفاتيح المستأجر أو Bearer Token لبيئات JWT.",
        ["Access Token"] = "رمز الوصول",
        ["Knowledge Base"] = "قاعدة المعرفة",
        ["KB Name"] = "اسم قاعدة المعرفة",
        ["KB ID"] = "معرّف قاعدة المعرفة",
        ["Optional exact target. Leave empty to match by name."] = "هدف دقيق اختياري. اتركه فارغًا للمطابقة بالاسم.",
        ["KB Description"] = "وصف قاعدة المعرفة",
        ["Used when creating or auto-creating a knowledge base."] = "يُستخدم عند إنشاء قاعدة معرفة أو إنشائها تلقائيًا.",
        ["Chunk Size"] = "حجم الجزء",
        ["Chunk size for new knowledge bases."] = "حجم الجزء لقواعد المعرفة الجديدة.",
        ["Chunk Overlap"] = "تداخل الأجزاء",
        ["Overlap applied between adjacent chunks."] = "التداخل المطبق بين الأجزاء المتجاورة.",
        ["Chat Model ID"] = "معرّف نموذج الدردشة",
        ["Embedding Model ID"] = "معرّف نموذج التضمين",
        ["Optional Embedding model from /api/v1/models. Leave empty to use the server default."] = "نموذج تضمين اختياري من /api/v1/models. اتركه فارغًا لاستخدام الإعداد الافتراضي للخادم.",
        ["Multimodal ID"] = "معرّف متعدد الوسائط",
        ["Optional VLLM model from /api/v1/models."] = "نموذج VLLM اختياري من /api/v1/models.",
        ["Auto-create the knowledge base when the configured name does not exist"] = "إنشاء قاعدة المعرفة تلقائيًا عندما لا يكون الاسم المكوّن موجودًا",
        ["Append export metadata to the synced Markdown content"] = "إلحاق بيانات التصدير الوصفية بمحتوى Markdown المتزامن",
        ["Enable parent-child chunking for newly created knowledge bases"] = "تمكين التجزئة الأب-الابن لقواعد المعرفة الجديدة",
        ["Test Connection"] = "اختبار الاتصال",
        ["Load Knowledge Bases"] = "تحميل قواعد المعرفة",
        ["Load Models"] = "تحميل النماذج",
        ["Create KB"] = "إنشاء قاعدة معرفة",
        ["WeKnora Sync"] = "مزامنة WeKnora",
        ["Select one or more completed conversion outputs, start a sync, then watch progress, ETA, logs, and resume state from the same screen."] = "اختر مخرج تحويل مكتملًا واحدًا أو أكثر، وابدأ المزامنة، ثم راقب التقدم والوقت المتوقع والسجلات وحالة الاستئناف من الشاشة نفسها.",
        ["Sync Selected Archives"] = "مزامنة الأرشيفات المحددة",
        ["Pause Selected Sync"] = "إيقاف المزامنة المحددة مؤقتًا",
        ["Resume Selected Sync"] = "استئناف المزامنة المحددة",
        ["Refresh Sync View"] = "تحديث عرض المزامنة",
        ["Select rows in the candidate grid to create sync tasks."] = "اختر صفوفًا من شبكة المرشحين لإنشاء مهام مزامنة.",
        ["Converted Archives Ready To Sync"] = "الأرشيفات المحولة الجاهزة للمزامنة",
        ["Each row represents a completed conversion task. The sync task will upload every completed article export from the selected archive to the configured WeKnora knowledge base."] = "يمثل كل صف مهمة تحويل مكتملة. سترفع مهمة المزامنة كل تصدير مقال مكتمل من الأرشيف المحدد إلى قاعدة المعرفة المكوّنة في WeKnora.",
        ["WeKnora Sync Tasks"] = "مهام مزامنة WeKnora",
        ["WeKnora Sync Logs"] = "سجلات مزامنة WeKnora",
        ["Search sync tasks by archive, knowledge base, status or error..."] = "ابحث في مهام المزامنة حسب الأرشيف أو قاعدة المعرفة أو الحالة أو الخطأ...",
        ["Search WeKnora sync logs by message or article URL..."] = "ابحث في سجلات WeKnora حسب الرسالة أو رابط المقالة...",
        ["Selected sync only"] = "المزامنة المحددة فقط",
        ["No WeKnora sync task selected."] = "لا توجد مهمة مزامنة WeKnora محددة.",
        ["Select a sync task row to scope logs."] = "اختر صف مهمة مزامنة لتحديد نطاق السجلات.",
        ["Use Refresh Sync View after changing filters."] = "استخدم زر تحديث عرض المزامنة بعد تغيير عوامل التصفية.",
        ["Choose an existing knowledge base from the server, or type a new KB name and click Create KB. New knowledge bases use the description, chunk size, chunk overlap, and parent-child settings above. Use Load Models to fetch live KnowledgeQA, Embedding, and VLLM model IDs from WeKnora before creating a KB or starting a sync."] = "اختر قاعدة معرفة موجودة من الخادم، أو اكتب اسم قاعدة معرفة جديدة ثم اضغط إنشاء قاعدة معرفة. تستخدم قواعد المعرفة الجديدة الوصف وحجم الجزء والتداخل وإعدادات الأب والابن أعلاه. استخدم تحميل النماذج لجلب معرّفات نماذج KnowledgeQA وEmbedding وVLLM الحية من WeKnora قبل إنشاء قاعدة معرفة أو بدء المزامنة."
    };

    private readonly IReadOnlyDictionary<string, string> _translations;

    private UiLocalizer(string languageCode, bool isRightToLeft, IReadOnlyDictionary<string, string> translations)
    {
        LanguageCode = languageCode;
        IsRightToLeft = isRightToLeft;
        _translations = translations;
    }

    public string LanguageCode { get; }

    public bool IsRightToLeft { get; }

    public string this[string englishText] => Get(englishText);

    public static UiLocalizer CreateForCurrentCulture()
    {
        var twoLetterCode = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return twoLetterCode switch
        {
            "zh" => new UiLocalizer("zh-CN", false, SimplifiedChinese),
            "ja" => new UiLocalizer("ja", false, Japanese),
            "es" => new UiLocalizer("es", false, Spanish),
            "ar" => new UiLocalizer("ar", true, Arabic),
            _ => new UiLocalizer("en", false, new Dictionary<string, string>())
        };
    }

    public string Get(string englishText)
    {
        return _translations.TryGetValue(englishText, out var translatedText)
            ? translatedText
            : englishText;
    }

    public string Format(string englishFormat, params object[] args)
    {
        return string.Format(CultureInfo.CurrentCulture, Get(englishFormat), args);
    }
}